/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Text */

#ifndef _Included_com_artifex_mupdf_fitz_Text
#define _Included_com_artifex_mupdf_fitz_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Text_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showGlyph
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;IIZ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showGlyph
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showString
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showString
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Text_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/TextWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
