/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_DocumentWriter */

#ifndef _Included_com_artifex_mupdf_fitz_DocumentWriter
#define _Included_com_artifex_mupdf_fitz_DocumentWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    newNativeDocumentWriter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_newNativeDocumentWriter
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    beginPage
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)Lcom/artifex/mupdf/fitz/Device;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_beginPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    endPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_endPage
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
