/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Shade */

#ifndef _Included_com_artifex_mupdf_fitz_Shade
#define _Included_com_artifex_mupdf_fitz_Shade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Shade
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Shade_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
