/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_FitzInputStream */

#ifndef _Included_com_artifex_mupdf_fitz_FitzInputStream
#define _Included_com_artifex_mupdf_fitz_FitzInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_FitzInputStream_MAX_SKIP_BUFFER_SIZE
#define com_artifex_mupdf_fitz_FitzInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    mark
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_mark
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    markSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_markSupported
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_available
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    readByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_readByte
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    readArray
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_readArray
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_FitzInputStream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_FitzInputStream_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
