/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_NativeDevice */

#ifndef _Included_com_artifex_mupdf_fitz_NativeDevice
#define _Included_com_artifex_mupdf_fitz_NativeDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_NORMAL
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_SCREEN
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_DARKEN
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_HUE
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_SATURATION
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_NativeDevice_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_NativeDevice_BLEND_LUMINOSITY 15L
/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_close
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FFI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillPath
  (JNIEnv *, jobject, jobject, jboolean, jobject, jobject, jfloatArray, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FFI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokePath
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipPath
  (JNIEnv *, jobject, jobject, jboolean, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokePath
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FFI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillText
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FFI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokeText
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokeText
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    ignoreText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_ignoreText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillShade
 * Signature: (Lcom/artifex/mupdf/fitz/Shade;Lcom/artifex/mupdf/fitz/Matrix;FI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillShade
  (JNIEnv *, jobject, jobject, jobject, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImage
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;FI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImage
  (JNIEnv *, jobject, jobject, jobject, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FFI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImageMask
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipImageMask
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    popClip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_popClip
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginMask
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ZLcom/artifex/mupdf/fitz/ColorSpace;[FI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginMask
  (JNIEnv *, jobject, jobject, jboolean, jobject, jfloatArray, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endMask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginGroup
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/ColorSpace;ZZIF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginGroup
  (JNIEnv *, jobject, jobject, jobject, jboolean, jboolean, jint, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginTile
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Rect;FFLcom/artifex/mupdf/fitz/Matrix;I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginTile
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endTile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endTile
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginLayer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginLayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endLayer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
