/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFDocument */

#ifndef _Included_com_artifex_mupdf_fitz_PDFDocument
#define _Included_com_artifex_mupdf_fitz_PDFDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newNative
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    findPage
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_findPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    getTrailer
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_getTrailer
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    countObjects
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_countObjects
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newNull
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newNull
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newBoolean
 * Signature: (Z)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newInteger
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newInteger
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newReal
 * Signature: (F)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newReal
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newString
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newByteString
 * Signature: ([B)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newByteString
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newName
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newIndirect
 * Signature: (II)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newIndirect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newArray
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newArray
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newDictionary
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newDictionary
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    createObject
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_createObject
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    deleteObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_deleteObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newPDFGraftMap
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFGraftMap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newPDFGraftMap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    graftObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_graftObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;Ljava/lang/Object;Z)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addStreamBuffer
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addStreamString
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Z)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addStreamString
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addPageBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ILcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/Buffer;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addPageBuffer
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addPageString
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ILcom/artifex/mupdf/fitz/PDFObject;Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addPageString
  (JNIEnv *, jobject, jobject, jint, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    insertPage
 * Signature: (ILcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_insertPage
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    deletePage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_deletePage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addImage
 * Signature: (Lcom/artifex/mupdf/fitz/Image;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addSimpleFont
 * Signature: (Lcom/artifex/mupdf/fitz/Font;I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addSimpleFont
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addCJKFont
 * Signature: (Lcom/artifex/mupdf/fitz/Font;IIZ)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addCJKFont
  (JNIEnv *, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addFont
 * Signature: (Lcom/artifex/mupdf/fitz/Font;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addFont
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    hasUnsavedChanges
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_hasUnsavedChanges
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    canBeSavedIncrementally
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_canBeSavedIncrementally
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    save
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_save
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    nativeSaveWithStream
 * Signature: (Lcom/artifex/mupdf/fitz/SeekableInputOutputStream;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_nativeSaveWithStream
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    enableJs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_enableJs
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    disableJs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_disableJs
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    isJsSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_isJsSupported
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    setJsEventListener
 * Signature: (Lcom/artifex/mupdf/fitz/PDFDocument/JsEventListener;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_setJsEventListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    calculate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_calculate
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    countVersions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_countVersions
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    countUnsavedVersions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_countUnsavedVersions
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    validateChangeHistory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_validateChangeHistory
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    wasPureXFA
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_wasPureXFA
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
