/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Image */

#ifndef _Included_com_artifex_mupdf_fitz_Image
#define _Included_com_artifex_mupdf_fitz_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Image_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Pixmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromPixmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getXResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getYResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getColorSpace
 * Signature: ()Lcom/artifex/mupdf/fitz/ColorSpace;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_getColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getNumberOfComponents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getBitsPerComponent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getBitsPerComponent
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getImageMask
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getImageMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getInterpolate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getInterpolate
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getMask
 * Signature: ()Lcom/artifex/mupdf/fitz/Image;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_getMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    toPixmap
 * Signature: ()Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_toPixmap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
