/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Context */

#ifndef _Included_com_artifex_mupdf_fitz_Context
#define _Included_com_artifex_mupdf_fitz_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Context_initNative
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    emptyStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Context_emptyStore
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    enableICC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Context_enableICC
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    disableICC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Context_disableICC
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    setAntiAliasLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Context_setAntiAliasLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
