/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PKCS7Signer */

#ifndef _Included_com_artifex_mupdf_fitz_PKCS7Signer
#define _Included_com_artifex_mupdf_fitz_PKCS7Signer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PKCS7Signer
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PKCS7Signer_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PKCS7Signer
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Signer;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_PKCS7Signer_newNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
