/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Buffer */

#ifndef _Included_com_artifex_mupdf_fitz_Buffer
#define _Included_com_artifex_mupdf_fitz_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    newNativeBuffer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Buffer_newNativeBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readBytes
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readBytes
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readBytesInto
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readBytesInto
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBytesFrom
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBytesFrom
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeRune
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeRune
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeLines
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeLines
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_save
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
