/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Font */

#ifndef _Included_com_artifex_mupdf_fitz_Font
#define _Included_com_artifex_mupdf_fitz_Font
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_Font_LATIN
#define com_artifex_mupdf_fitz_Font_LATIN 0L
#undef com_artifex_mupdf_fitz_Font_GREEK
#define com_artifex_mupdf_fitz_Font_GREEK 1L
#undef com_artifex_mupdf_fitz_Font_CYRILLIC
#define com_artifex_mupdf_fitz_Font_CYRILLIC 2L
#undef com_artifex_mupdf_fitz_Font_ADOBE_CNS
#define com_artifex_mupdf_fitz_Font_ADOBE_CNS 0L
#undef com_artifex_mupdf_fitz_Font_ADOBE_GB
#define com_artifex_mupdf_fitz_Font_ADOBE_GB 1L
#undef com_artifex_mupdf_fitz_Font_ADOBE_JAPAN
#define com_artifex_mupdf_fitz_Font_ADOBE_JAPAN 2L
#undef com_artifex_mupdf_fitz_Font_ADOBE_KOREA
#define com_artifex_mupdf_fitz_Font_ADOBE_KOREA 3L
/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Font_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    newNative
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Font_newNative
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Font_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    encodeCharacter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Font_encodeCharacter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    advanceGlyph
 * Signature: (IZ)F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_Font_advanceGlyph
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
