/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Device */

#ifndef _Included_com_artifex_mupdf_fitz_Device
#define _Included_com_artifex_mupdf_fitz_Device
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_Device_BLEND_NORMAL
#define com_artifex_mupdf_fitz_Device_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_Device_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_Device_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_Device_BLEND_SCREEN
#define com_artifex_mupdf_fitz_Device_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_Device_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_Device_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_Device_BLEND_DARKEN
#define com_artifex_mupdf_fitz_Device_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_Device_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_Device_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_Device_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_Device_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_Device_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_Device_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_Device_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_Device_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_Device_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_Device_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_Device_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_Device_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_Device_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_Device_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_Device_BLEND_HUE
#define com_artifex_mupdf_fitz_Device_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_Device_BLEND_SATURATION
#define com_artifex_mupdf_fitz_Device_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_Device_BLEND_COLOR
#define com_artifex_mupdf_fitz_Device_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_Device_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_Device_BLEND_LUMINOSITY 15L
/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Device_newNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
