/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PKCS7Verifier */

#ifndef _Included_com_artifex_mupdf_fitz_PKCS7Verifier
#define _Included_com_artifex_mupdf_fitz_PKCS7Verifier
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierOK
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierOK 0L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNoSignature
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNoSignature 1L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNoCertificate
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNoCertificate 2L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierDigestFailure
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierDigestFailure 3L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierSelfSigned
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierSelfSigned 4L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierSelfSignedInChain
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierSelfSignedInChain 5L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNotTrusted
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierNotTrusted 6L
#undef com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierUnknown
#define com_artifex_mupdf_fitz_PKCS7Verifier_PKCS7VerifierUnknown -1L
/*
 * Class:     com_artifex_mupdf_fitz_PKCS7Verifier
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PKCS7Verifier_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PKCS7Verifier
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Verifier;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_PKCS7Verifier_newNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
