/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFObject */

#ifndef _Included_com_artifex_mupdf_fitz_PDFObject
#define _Included_com_artifex_mupdf_fitz_PDFObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isIndirect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isIndirect
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isNull
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isNull
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isInteger
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isInteger
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isReal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isReal
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isNumber
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isString
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isString
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isName
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isArray
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isArray
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isDictionary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isDictionary
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isStream
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asInteger
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asIndirect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asIndirect
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asString
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    asByteString
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_asByteString
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toString
 * Signature: (ZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toString
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    resolve
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_resolve
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    readStream
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_readStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    readRawStream
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_readRawStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeStreamBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeStreamString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeStreamString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeRawStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeRawStreamBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeRawStreamString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeRawStreamString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    getArray
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    getDictionary
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_getDictionary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    getDictionaryKey
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_getDictionaryKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayBoolean
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayBoolean
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayInteger
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayInteger
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayPDFObject
 * Signature: (ILcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayPDFObject
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringFloat
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringPDFObject
 * Signature: (Ljava/lang/String;Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringPDFObject
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectBoolean
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectBoolean
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectInteger
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectInteger
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectFloat
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectFloat
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectString
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectString
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectPDFObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectPDFObject
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectRect
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/Rect;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectRect
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectMatrix
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectMatrix
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectDate
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectDate
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteDictionaryString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteDictionaryString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteDictionaryPDFObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteDictionaryPDFObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFObject_size
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    pushBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_pushBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    pushInteger
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_pushInteger
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    pushFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_pushFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    pushString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_pushString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    pushPDFObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_pushPDFObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
