/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Document */

#ifndef _Included_com_artifex_mupdf_fitz_Document
#define _Included_com_artifex_mupdf_fitz_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    openNativeWithPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/artifex/mupdf/fitz/Document;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_openNativeWithPath
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    openNativeWithBuffer
 * Signature: (Ljava/lang/String;[B[B)Lcom/artifex/mupdf/fitz/Document;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_openNativeWithBuffer
  (JNIEnv *, jclass, jstring, jbyteArray, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    openNativeWithStream
 * Signature: (Ljava/lang/String;Lcom/artifex/mupdf/fitz/SeekableInputStream;Lcom/artifex/mupdf/fitz/SeekableInputStream;)Lcom/artifex/mupdf/fitz/Document;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_openNativeWithStream
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    openNativeWithPathAndStream
 * Signature: (Ljava/lang/String;Lcom/artifex/mupdf/fitz/SeekableInputStream;)Lcom/artifex/mupdf/fitz/Document;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_openNativeWithPathAndStream
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    recognize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_recognize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    saveAccelerator
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_saveAccelerator
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    outputAccelerator
 * Signature: (Lcom/artifex/mupdf/fitz/SeekableOutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_outputAccelerator
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    needsPassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_needsPassword
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    authenticatePassword
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_authenticatePassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    countChapters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Document_countChapters
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    countPages
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Document_countPages
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadPage
 * Signature: (II)Lcom/artifex/mupdf/fitz/Page;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_loadPage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    resolveLink
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/Location;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_resolveLink
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadOutline
 * Signature: ()[Lcom/artifex/mupdf/fitz/Outline;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Document_loadOutline
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    getMetaData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Document_getMetaData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    isReflowable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_isReflowable
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    layout
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_layout
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    findBookmark
 * Signature: (J)Lcom/artifex/mupdf/fitz/Location;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_findBookmark
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    makeBookmark
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Document_makeBookmark
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    isUnencryptedPDF
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_isUnencryptedPDF
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
