/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFPage */

#ifndef _Included_com_artifex_mupdf_fitz_PDFPage
#define _Included_com_artifex_mupdf_fitz_PDFPage
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_NONE
#define com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_NONE 0L
#undef com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_REMOVE
#define com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_REMOVE 1L
#undef com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_PIXELS
#define com_artifex_mupdf_fitz_PDFPage_REDACT_IMAGE_PIXELS 2L
/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    getAnnotations
 * Signature: ()[Lcom/artifex/mupdf/fitz/PDFAnnotation;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_PDFPage_getAnnotations
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    createAnnotation
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFAnnotation;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFPage_createAnnotation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    deleteAnnotation
 * Signature: (Lcom/artifex/mupdf/fitz/PDFAnnotation;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFPage_deleteAnnotation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    applyRedactions
 * Signature: (ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFPage_applyRedactions
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    update
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFPage_update
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFPage
 * Method:    getWidgetsNative
 * Signature: ()[Lcom/artifex/mupdf/fitz/PDFWidget;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_PDFPage_getWidgetsNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
