/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Cookie */

#ifndef _Included_com_artifex_mupdf_fitz_Cookie
#define _Included_com_artifex_mupdf_fitz_Cookie
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Cookie_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_abort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
