/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_DisplayList */

#ifndef _Included_com_artifex_mupdf_fitz_DisplayList
#define _Included_com_artifex_mupdf_fitz_DisplayList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DisplayList_newNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DisplayList_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    toStructuredText
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/StructuredText;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DisplayList_toStructuredText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_DisplayList_search
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_run
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
