/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFAnnotation */

#ifndef _Included_com_artifex_mupdf_fitz_PDFAnnotation
#define _Included_com_artifex_mupdf_fitz_PDFAnnotation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_TEXT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_TEXT 0L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_LINK
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_LINK 1L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_FREE_TEXT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_FREE_TEXT 2L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_LINE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_LINE 3L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SQUARE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SQUARE 4L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_CIRCLE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_CIRCLE 5L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POLYGON
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POLYGON 6L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POLY_LINE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POLY_LINE 7L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_HIGHLIGHT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_HIGHLIGHT 8L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_UNDERLINE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_UNDERLINE 9L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SQUIGGLY
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SQUIGGLY 10L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_STRIKE_OUT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_STRIKE_OUT 11L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_REDACT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_REDACT 12L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_STAMP
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_STAMP 13L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_CARET
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_CARET 14L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_INK
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_INK 15L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POPUP
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_POPUP 16L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_FILE_ATTACHMENT
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_FILE_ATTACHMENT 17L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SOUND
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SOUND 18L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_MOVIE
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_MOVIE 19L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_WIDGET
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_WIDGET 20L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SCREEN
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_SCREEN 21L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_PRINTER_MARK
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_PRINTER_MARK 22L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_TRAP_NET
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_TRAP_NET 23L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_WATERMARK
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_WATERMARK 24L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_3D
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_3D 25L
#undef com_artifex_mupdf_fitz_PDFAnnotation_TYPE_UNKNOWN
#define com_artifex_mupdf_fitz_PDFAnnotation_TYPE_UNKNOWN -1L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_NONE
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_NONE 0L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_SQUARE
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_SQUARE 1L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_CIRCLE
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_CIRCLE 2L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_DIAMOND
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_DIAMOND 3L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_OPEN_ARROW
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_OPEN_ARROW 4L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_CLOSED_ARROW
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_CLOSED_ARROW 5L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_BUTT
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_BUTT 6L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_R_OPEN_ARROW
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_R_OPEN_ARROW 7L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_R_CLOSED_ARROW
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_R_CLOSED_ARROW 8L
#undef com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_SLASH
#define com_artifex_mupdf_fitz_PDFAnnotation_LINE_ENDING_SLASH 9L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_INVISIBLE
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_INVISIBLE 1L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_HIDDEN
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_HIDDEN 2L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_PRINT
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_PRINT 4L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_ZOOM
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_ZOOM 8L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_ROTATE
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_ROTATE 16L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_VIEW
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_NO_VIEW 32L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_READ_ONLY
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_READ_ONLY 64L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_LOCKED
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_LOCKED 128L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_TOGGLE_NO_VIEW
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_TOGGLE_NO_VIEW 256L
#undef com_artifex_mupdf_fitz_PDFAnnotation_IS_LOCKED_CONTENTS
#define com_artifex_mupdf_fitz_PDFAnnotation_IS_LOCKED_CONTENTS 512L
/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getBounds
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    toDisplayList
 * Signature: ()Lcom/artifex/mupdf/fitz/DisplayList;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_toDisplayList
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getContents
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getContents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setContents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setContents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getRect
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getRect
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setRect
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getBorder
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getBorder
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setBorder
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setBorder
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setColor
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setColor
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getInteriorColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getInteriorColor
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setInteriorColor
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setInteriorColor
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getAuthor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getAuthor
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setAuthor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setAuthor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getCreationDateNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getCreationDateNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setCreationDate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setCreationDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getModificationDateNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getModificationDateNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setModificationDate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setModificationDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getLineEndingStyles
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getLineEndingStyles
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setLineEndingStyles
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setLineEndingStyles
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getQuadPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getQuadPointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getQuadPoint
 * Signature: (I)Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getQuadPoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    clearQuadPoints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_clearQuadPoints
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    addQuadPoint
 * Signature: (Lcom/artifex/mupdf/fitz/Quad;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_addQuadPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getVertex
 * Signature: (I)Lcom/artifex/mupdf/fitz/Point;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getVertex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    clearVertices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_clearVertices
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    addVertex
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_addVertex
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getInkListCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getInkListCount
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getInkListStrokeCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getInkListStrokeCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getInkListStrokeVertex
 * Signature: (II)Lcom/artifex/mupdf/fitz/Point;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getInkListStrokeVertex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    clearInkList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_clearInkList
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    addInkListStroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_addInkListStroke
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    addInkListStrokeVertex
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_addInkListStrokeVertex
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    getIcon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_getIcon
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setIcon
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setIcon
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    setIsOpen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_setIsOpen
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventEnter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventEnter
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventExit
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventDown
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventUp
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventFocus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventFocus
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    eventBlur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_eventBlur
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFAnnotation
 * Method:    update
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFAnnotation_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
