/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Rect */

#ifndef _Included_com_artifex_mupdf_fitz_Rect
#define _Included_com_artifex_mupdf_fitz_Rect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Rect
 * Method:    adjustForStroke
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Rect_adjustForStroke
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
