/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Path */

#ifndef _Included_com_artifex_mupdf_fitz_Path
#define _Included_com_artifex_mupdf_fitz_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    cloneNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_cloneNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    currentPoint
 * Signature: ()Lcom/artifex/mupdf/fitz/Point;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_currentPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToV
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToY
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToY
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    rect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_rect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    closePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_closePath
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    transform
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_transform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/PathWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
