/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_StructuredText */

#ifndef _Included_com_artifex_mupdf_fitz_StructuredText
#define _Included_com_artifex_mupdf_fitz_StructuredText
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_StructuredText_SELECT_CHARS
#define com_artifex_mupdf_fitz_StructuredText_SELECT_CHARS 0L
#undef com_artifex_mupdf_fitz_StructuredText_SELECT_WORDS
#define com_artifex_mupdf_fitz_StructuredText_SELECT_WORDS 1L
#undef com_artifex_mupdf_fitz_StructuredText_SELECT_LINES
#define com_artifex_mupdf_fitz_StructuredText_SELECT_LINES 2L
/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StructuredText_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_StructuredText_search
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    highlight
 * Signature: (Lcom/artifex/mupdf/fitz/Point;Lcom/artifex/mupdf/fitz/Point;)[Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_StructuredText_highlight
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    snapSelection
 * Signature: (Lcom/artifex/mupdf/fitz/Point;Lcom/artifex/mupdf/fitz/Point;I)Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_StructuredText_snapSelection
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    copy
 * Signature: (Lcom/artifex/mupdf/fitz/Point;Lcom/artifex/mupdf/fitz/Point;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_StructuredText_copy
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/StructuredTextWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StructuredText_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
