/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFWidget */

#ifndef _Included_com_artifex_mupdf_fitz_PDFWidget
#define _Included_com_artifex_mupdf_fitz_PDFWidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_TEXT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_TEXT 0L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_LINK
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_LINK 1L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_FREE_TEXT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_FREE_TEXT 2L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_LINE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_LINE 3L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_SQUARE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_SQUARE 4L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_CIRCLE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_CIRCLE 5L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_POLYGON
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_POLYGON 6L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_POLY_LINE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_POLY_LINE 7L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_HIGHLIGHT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_HIGHLIGHT 8L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_UNDERLINE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_UNDERLINE 9L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_SQUIGGLY
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_SQUIGGLY 10L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_STRIKE_OUT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_STRIKE_OUT 11L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_REDACT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_REDACT 12L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_STAMP
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_STAMP 13L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_CARET
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_CARET 14L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_INK
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_INK 15L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_POPUP
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_POPUP 16L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_FILE_ATTACHMENT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_FILE_ATTACHMENT 17L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_SOUND
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_SOUND 18L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_MOVIE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_MOVIE 19L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_WIDGET
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_WIDGET 20L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_SCREEN
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_SCREEN 21L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_PRINTER_MARK
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_PRINTER_MARK 22L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_TRAP_NET
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_TRAP_NET 23L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_WATERMARK
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_WATERMARK 24L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_3D
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_3D 25L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_UNKNOWN
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_UNKNOWN -1L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_NONE
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_NONE 0L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_SQUARE
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_SQUARE 1L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_CIRCLE
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_CIRCLE 2L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_DIAMOND
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_DIAMOND 3L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_OPEN_ARROW
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_OPEN_ARROW 4L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_CLOSED_ARROW
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_CLOSED_ARROW 5L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_BUTT
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_BUTT 6L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_R_OPEN_ARROW
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_R_OPEN_ARROW 7L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_R_CLOSED_ARROW
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_R_CLOSED_ARROW 8L
#undef com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_SLASH
#define com_artifex_mupdf_fitz_PDFWidget_LINE_ENDING_SLASH 9L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_INVISIBLE
#define com_artifex_mupdf_fitz_PDFWidget_IS_INVISIBLE 1L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_HIDDEN
#define com_artifex_mupdf_fitz_PDFWidget_IS_HIDDEN 2L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_PRINT
#define com_artifex_mupdf_fitz_PDFWidget_IS_PRINT 4L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_NO_ZOOM
#define com_artifex_mupdf_fitz_PDFWidget_IS_NO_ZOOM 8L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_NO_ROTATE
#define com_artifex_mupdf_fitz_PDFWidget_IS_NO_ROTATE 16L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_NO_VIEW
#define com_artifex_mupdf_fitz_PDFWidget_IS_NO_VIEW 32L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_READ_ONLY
#define com_artifex_mupdf_fitz_PDFWidget_IS_READ_ONLY 64L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_LOCKED
#define com_artifex_mupdf_fitz_PDFWidget_IS_LOCKED 128L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_TOGGLE_NO_VIEW
#define com_artifex_mupdf_fitz_PDFWidget_IS_TOGGLE_NO_VIEW 256L
#undef com_artifex_mupdf_fitz_PDFWidget_IS_LOCKED_CONTENTS
#define com_artifex_mupdf_fitz_PDFWidget_IS_LOCKED_CONTENTS 512L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_UNKNOWN
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_UNKNOWN 0L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_BUTTON
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_BUTTON 1L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_CHECKBOX
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_CHECKBOX 2L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_COMBOBOX
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_COMBOBOX 3L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_LISTBOX
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_LISTBOX 4L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_RADIOBUTTON
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_RADIOBUTTON 5L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_SIGNATURE
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_SIGNATURE 6L
#undef com_artifex_mupdf_fitz_PDFWidget_TYPE_TEXT
#define com_artifex_mupdf_fitz_PDFWidget_TYPE_TEXT 7L
#undef com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_NONE
#define com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_NONE 0L
#undef com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_NUMBER
#define com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_NUMBER 1L
#undef com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_SPECIAL
#define com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_SPECIAL 2L
#undef com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_DATE
#define com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_DATE 3L
#undef com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_TIME
#define com_artifex_mupdf_fitz_PDFWidget_TX_FORMAT_TIME 4L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_READ_ONLY
#define com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_READ_ONLY 1L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_REQUIRED
#define com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_REQUIRED 2L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_NO_EXPORT
#define com_artifex_mupdf_fitz_PDFWidget_PDF_FIELD_IS_NO_EXPORT 4L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_MULTILINE
#define com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_MULTILINE 4096L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_PASSWORD
#define com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_PASSWORD 8192L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_COMB
#define com_artifex_mupdf_fitz_PDFWidget_PDF_TX_FIELD_IS_COMB 16777216L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_NO_TOGGLE_TO_OFF
#define com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_NO_TOGGLE_TO_OFF 16384L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_RADIO
#define com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_RADIO 32768L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_PUSHBUTTON
#define com_artifex_mupdf_fitz_PDFWidget_PDF_BTN_FIELD_IS_PUSHBUTTON 65536L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_COMBO
#define com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_COMBO 131072L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_EDIT
#define com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_EDIT 262144L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_SORT
#define com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_SORT 524288L
#undef com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_MULTI_SELECT
#define com_artifex_mupdf_fitz_PDFWidget_PDF_CH_FIELD_IS_MULTI_SELECT 2097152L
/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_getValue
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    setValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_setValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    toggle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_toggle
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    setTextValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_setTextValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    textQuads
 * Signature: ()[Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_textQuads
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    setEditing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_setEditing
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    isEditing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_isEditing
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    setChoiceValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_setChoiceValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    sign
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Signer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_sign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    checkCertificate
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Verifier;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_checkCertificate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    checkDigest
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Verifier;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_checkDigest
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    incrementalChangeAfterSigning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_incrementalChangeAfterSigning
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    getDesignatedName
 * Signature: (Lcom/artifex/mupdf/fitz/PKCS7Verifier;)Lcom/artifex/mupdf/fitz/PKCS7DesignatedName;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_getDesignatedName
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    validateSignature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_validateSignature
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFWidget
 * Method:    isSigned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFWidget_isSigned
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
