/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_PDFGraftMap */

#ifndef _Included_com_artifex_mupdf_fitz_PDFGraftMap
#define _Included_com_artifex_mupdf_fitz_PDFGraftMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFGraftMap
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFGraftMap_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFGraftMap
 * Method:    graftObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFGraftMap_graftObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
