/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_StrokeState */

#ifndef _Included_com_artifex_mupdf_fitz_StrokeState
#define _Included_com_artifex_mupdf_fitz_StrokeState
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_StrokeState_LINE_CAP_BUTT
#define com_artifex_mupdf_fitz_StrokeState_LINE_CAP_BUTT 0L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_CAP_ROUND
#define com_artifex_mupdf_fitz_StrokeState_LINE_CAP_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_CAP_SQUARE
#define com_artifex_mupdf_fitz_StrokeState_LINE_CAP_SQUARE 2L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_CAP_TRIANGLE
#define com_artifex_mupdf_fitz_StrokeState_LINE_CAP_TRIANGLE 3L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_MITER
#define com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_MITER 0L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_ROUND
#define com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_BEVEL
#define com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_BEVEL 2L
#undef com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_MITER_XPS
#define com_artifex_mupdf_fitz_StrokeState_LINE_JOIN_MITER_XPS 3L
/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StrokeState_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    newNative
 * Signature: (IIIIFFF[F)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_StrokeState_newNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getStartCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getStartCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getEndCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getEndCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineJoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineJoin
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getMiterLimit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getMiterLimit
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashPhase
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashPhase
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashes
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
