/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_ColorSpace */

#ifndef _Included_com_artifex_mupdf_fitz_ColorSpace
#define _Included_com_artifex_mupdf_fitz_ColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceGray
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceGray
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceRGB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceRGB
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceBGR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceBGR
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceCMYK
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceCMYK
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_getNumberOfComponents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
