/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Page */

#ifndef _Included_com_artifex_mupdf_fitz_Page
#define _Included_com_artifex_mupdf_fitz_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getBounds
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    runPageContents
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_runPageContents
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    runPageAnnots
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_runPageAnnots
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    runPageWidgets
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_runPageWidgets
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getLinks
 * Signature: ()[Lcom/artifex/mupdf/fitz/Link;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_getLinks
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;ZZ)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toDisplayList
 * Signature: (Z)Lcom/artifex/mupdf/fitz/DisplayList;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toDisplayList
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toStructuredText
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/StructuredText;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toStructuredText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Quad;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_search
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    textAsHtml
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_Page_textAsHtml
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
